config/routes.rb
Rails.application.routes.draw do
  resources :details

  resources :guns

  resources :people

  resources :casos

  devise_for :users

  
  authenticated do
    root :to => 'home#home', :as => 'authenticated_user'
    get 'casos' => 'casos#index'
    get 'casos/new' => 'casos#new'
    post 'casos/create' => 'casos#create'
  end

  root :to => 'home#index', :as => 'unathenticated'

end

app/models/caso.rb
class Caso < ActiveRecord::Base
	belongs_to :user
	has_many :people
	has_one :detail
end

app/controllers/casos_controller.rb
class CasosController < ApplicationController
  before_action :set_caso, only: [:show, :edit, :update, :destroy]

  # GET /casos
  # GET /casos.json
  def index
    @user = current_user
    @casos = @user.casos
  end

  # GET /casos/1
  # GET /casos/1.json
  def show
  end

  # GET /casos/new
  def new
    @caso = Caso.new
  end

  # GET /casos/1/edit
  def edit
  end

  # POST /casos
  # POST /casos.json
  def create
    @caso = Caso.new(caso_params)
    @caso.user_id = current_user.id
    respond_to do |format|
      if @caso.save
        format.html { redirect_to @caso, notice: 'Caso was successfully created.' }
        format.json { render :show, status: :created, location: @caso }
      else
        format.html { render :new }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casos/1
  # PATCH/PUT /casos/1.json
  def update
    respond_to do |format|
      if @caso.update(caso_params)
        format.html { redirect_to @caso, notice: 'Caso was successfully updated.' }
        format.json { render :show, status: :ok, location: @caso }
      else
        format.html { render :edit }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casos/1
  # DELETE /casos/1.json
  def destroy
    @caso.destroy
    respond_to do |format|
      format.html { redirect_to casos_url, notice: 'Caso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caso
      @caso = Caso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caso_params
      params.require(:caso).permit(:casename, :status, :user_id)
    end
end

app/helpers/casos_helper.rb
module CasosHelper
end

app/views/casos/_form.html.erb
<%= form_for(@caso) do |f| %>
  <% if @caso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caso.errors.count, "error") %> prohibited this caso from being saved:</h2>

      <ul>
      <% @caso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :casename %><br>
    <%= f.text_field :casename %>
  </div>
  <div class="field">
    <%= f.label :victname %><br>
    <%= f.text_field :victname %>
  </div>
  <div class="field">
    <%= f.label :date_occu %><br>
    <%= f.date_select :date_occu %>
  </div>
  <div class="field">
    <%= f.label :place_occu %><br>
    <%= f.text_field :place_occu %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/casos/edit.html.erb
<h1>Editing caso</h1>

<%= render 'form' %>

<%= link_to 'Show', @caso %> |
<%= link_to 'Back', casos_path %>

app/views/casos/index.html.erb
<h1>Listing casos</h1>

<table>
  <thead>
    <tr>
      <th>Casename</th>
      <th>Victname</th>
      <th>Date occu</th>
      <th>Place occu</th>
      <th>Desc</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @casos.each do |caso| %>
      <tr>
        <td><%= caso.casename %></td>
        
        <td><%= caso.victname %></td>
        <td><%= caso.date_occu %></td>
        <td><%= caso.place_occu %></td>
        <td><%= caso.desc %></td>
        <td><%= caso.status %></td>
        <td><%= caso.user_id %></td>
        <td><%= link_to 'Show', caso %></td>
        <td><%= link_to 'Edit', edit_caso_path(caso) %></td>
        <td><%= link_to 'Destroy', caso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caso', new_caso_path %>

app/views/casos/new.html.erb
<h1>New caso</h1>

<%= render 'form' %>

<%= link_to 'Back', casos_path %>

app/views/casos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Casename:</strong>
  <%= @caso.casename %>
</p>

<p>
  <strong>Victname:</strong>
  <%= @caso.victname %>
</p>

<p>
  <strong>Date occu:</strong>
  <%= @caso.date_occu %>
</p>

<p>
  <strong>Place occu:</strong>
  <%= @caso.place_occu %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @caso.desc %>
</p>

<p>
  <strong>Status:</strong>
  <%= @caso.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @caso.user_id %>
</p>

<%= link_to 'Edit', edit_caso_path(@caso) %> |
<%= link_to 'Back', casos_path %>