config/routes.rb
Rails.application.routes.draw do
  resources :details

  resources :guns

  resources :people

  resources :casos

  devise_for :users

  
  authenticated do
    root :to => 'home#home', :as => 'authenticated_user'
    get 'casos' => 'casos#index'
    get 'casos/new' => 'casos#new'
    post 'casos/create' => 'casos#create'
  end

  root :to => 'home#index', :as => 'unathenticated'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
	belongs_to :caso
	has_many :guns, through: :weapon
	has_many :people, through: :primesuspect
	has_many :people, through: :personinvolved
	has_many :people, through: :guilty
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:weapon, :primesuspect, :personinvolved, :evid_collected, :evid_inv, :notes, :guilty)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weapon %><br>
    <%= f.number_field :weapon %>
  </div>
  <div class="field">
    <%= f.label :primesuspect %><br>
    <%= f.number_field :primesuspect %>
  </div>
  <div class="field">
    <%= f.label :personinvolved %><br>
    <%= f.number_field :personinvolved %>
  </div>
  <div class="field">
    <%= f.label :evid_collected %><br>
    <%= f.text_area :evid_collected %>
  </div>
  <div class="field">
    <%= f.label :evid_inv %><br>
    <%= f.text_area :evid_inv %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :guilty %><br>
    <%= f.number_field :guilty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<h1>Listing details</h1>

<table>
  <thead>
    <tr>
      <th>Weapon</th>
      <th>Primesuspect</th>
      <th>Personinvolved</th>
      <th>Evid collected</th>
      <th>Evid inv</th>
      <th>Notes</th>
      <th>Guilty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.weapon %></td>
        <td><%= detail.primesuspect %></td>
        <td><%= detail.personinvolved %></td>
        <td><%= detail.evid_collected %></td>
        <td><%= detail.evid_inv %></td>
        <td><%= detail.notes %></td>
        <td><%= detail.guilty %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weapon:</strong>
  <%= @detail.weapon %>
</p>

<p>
  <strong>Primesuspect:</strong>
  <%= @detail.primesuspect %>
</p>

<p>
  <strong>Personinvolved:</strong>
  <%= @detail.personinvolved %>
</p>

<p>
  <strong>Evid collected:</strong>
  <%= @detail.evid_collected %>
</p>

<p>
  <strong>Evid inv:</strong>
  <%= @detail.evid_inv %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @detail.notes %>
</p>

<p>
  <strong>Guilty:</strong>
  <%= @detail.guilty %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>