config/routes.rb
Rails.application.routes.draw do
  resources :details

  resources :guns

  resources :people

  resources :casos

  devise_for :users

  
  authenticated do
    root :to => 'home#home', :as => 'authenticated_user'
    get 'casos' => 'casos#index'
    get 'casos/new' => 'casos#new'
    post 'casos/create' => 'casos#create'
  end

  root :to => 'home#index', :as => 'unathenticated'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Detective" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

	<p class="navbar-text pull-right">
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
	</p>
<% if user_signed_in? %>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          	

          <a class="brand" href="#">Detective</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to 'Casos', casos_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'Detalles', details_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'Personas', people_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'Armas', guns_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'Edit user', edit_user_registration_path, :class => 'navbar-link' %></li>
              
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            </ul>
          </div><!--/.nav-collapse -->


        </div>
      </div>
    </div>
<% end %>
    <div id="content" class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          
        </div><!--/row-->

      <footer>
        <p>&copy; Grupo 25 - BD2014-1</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="HYPE Trends">
  <meta name="author" content="REFRAME S.A.">
  <!-- <link rel="icon" href="../../favicon.ico"> -->
  <title>HYPE Trends</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'public' %>
  <%= javascript_include_tag 'public' %>
  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="https://raw.githubusercontent.com/twbs/bootstrap/master/docs/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="https://raw.githubusercontent.com/twbs/bootstrap/master/docs/assets/js/ie-emulation-modes-warning.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="https://raw.githubusercontent.com/twbs/bootstrap/master/docs/assets/js/ie10-viewport-bug-workaround.js"></script>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <div class="masthead clearfix">
          <div class="inner">
            <ul class="nav masthead-nav">
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            </ul>
          </div>
        </div>
        <div class="inner cover">
            <%= image_tag("hype.jpg", :alt => "Hype Trends") %>
            <br/>
            <br/>
            <br/>
            <a href="/users/sign_up?kind=i" class="btn btn-lg btn-default">Influenciador</a>
            <a href="/users/sign_up?kind=b" class="btn btn-lg btn-default">Marca</a>
        </div>
        <div class="mastfoot">
          <div class="inner">
            <p>Desarrollado por <a href="http://reframe.cl">Reframe S.A.</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>